import { useRouter } from "next/router";
import { allProduct } from "../../components/data";
import Head from "next/head";

const ViewItem = () => {

    const router = useRouter();

    const data = allProduct?.filter(i => i.id == router.query.itemId)[0]

    return (
        <div className="container pt-4">
            <Head>
                <title>{data?.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.jpg" />
            </Head>
            <div className="row mt-5 pt-5">
                <div className="col-sm-6 col-md-5 border p-4 my-3 text-center">
                    <img src={data?.image?.src} className="" style={{ height: "400px" }} />
                </div>
                <div className="col-sm-6 col-md-7 p-4 my-3">
                    <p className="p-0 m-0 text-danger">{data?.company}</p>
                    <h3 className="m-0 p-0 fw-bold">{data?.name}</h3>
                    <hr className="mb-0 mt-4" />
                    <h5>{data?.title}</h5>
                    <p style={{ fontSize: "16px" }}>{data?.text}</p>
                    <h3 className="text-danger">{data?.price} ₽</h3>
                    <button className="btn btn-outline-danger me-2">Back to product</button>
                    <button className="btn btn-outline-primary">Add to card</button>
                </div>
            </div>
        </div>
    )
}
export default ViewItem;